### PR TITLE
Add info on how to display the distro logo

### PR DESCRIPTION
**Pull request by axelrindle**
I edited a script file to additionally display the Ubuntu logo and thought it would be useful for others to know on how to accomplish this.

### CODE REVIEW

**Comment by qualk** [comment]
Could you please add an image example with the Ubuntu logo to the README.md?
Because I want to see what it looks like before using it :)

**Comment by axelrindle** [comment]
@qualk Done :grin:

**Comment by qualk** [comment]
Oooooooooooooooooooooh, looking nice.
Can you pls also add Arch to the readme?
Also, is there support for custom images?

**Comment by axelrindle** [comment]
> Also, is there support for custom images?

[As you can read in the updated README](https://github.com/adi1090x/plymouth-themes/pull/18/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5), you can use any image you like. You could even add multiple images. This PR just adds an example on how to get a custom image into your boot screen.

> Can you pls also add Arch to the readme?

I guess you mean another example image. No, I don't think I will add another one. One example should be enough to get an idea of what this looks like.

**Comment by adi1090x** [comment]
Awesome!

**Pull request merged**
